<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-TKF8PN85" failures="2" tests="2" name="Test" time="65.385" errors="0" timestamp="2024-09-28T14:14:10 EDT">
  <testcase classname="tests.LoginTest" name="login" time="16.305">
    <failure type="java.lang.AssertionError" message="expected [Sucessfull] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Sucessfull] but found [Failure]
at tests.LoginTest.login(LoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="15.083">
    <failure type="java.lang.AssertionError" message="expected [failure] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [failure] but found [Failure]
at tests.LoginTest.login(LoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
